{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int change = 0;\n", "entropy": 3.3817026615142822, "length": 256, "finished": false, "message": null, "duration_seconds": 8.278815746307373}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int change = 0;\n", "entropy": 3.3817026615142822, "length": 256, "finished": false, "message": null, "duration_seconds": 8.088384866714478}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int change = 0;\n", "entropy": 3.3817026615142822, "length": 256, "finished": false, "message": null, "duration_seconds": 8.130863666534424}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int change = 0;\n", "entropy": 3.3817026615142822, "length": 256, "finished": false, "message": null, "duration_seconds": 8.261854648590088}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int change = 0;\n", "entropy": 3.3817026615142822, "length": 256, "finished": false, "message": null, "duration_seconds": 8.02157473564148}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int sum = 0;\n", "entropy": 3.506784200668335, "length": 256, "finished": false, "message": null, "duration_seconds": 8.045742988586426}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int sum = 0;\n", "entropy": 3.506784200668335, "length": 256, "finished": false, "message": null, "duration_seconds": 8.03062129020691}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        if (total == 1) {\n", "entropy": 3.72959566116333, "length": 256, "finished": false, "message": null, "duration_seconds": 8.085424184799194}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int result = 0;\n", "entropy": 3.866445779800415, "length": 256, "finished": false, "message": null, "duration_seconds": 8.089093446731567}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int count = 0;\n", "entropy": 3.9165475368499756, "length": 256, "finished": false, "message": null, "duration_seconds": 8.147572755813599}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int count = 0;\n", "entropy": 3.9165475368499756, "length": 256, "finished": false, "message": null, "duration_seconds": 8.065374612808228}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int count = 0;\n", "entropy": 3.9165475368499756, "length": 256, "finished": false, "message": null, "duration_seconds": 8.184201955795288}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int count = 0;\n", "entropy": 3.9165475368499756, "length": 256, "finished": false, "message": null, "duration_seconds": 8.084097862243652}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        \n", "entropy": 3.9832653999328613, "length": 256, "finished": false, "message": null, "duration_seconds": 9.34738540649414}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        \n", "entropy": 3.9832653999328613, "length": 256, "finished": false, "message": null, "duration_seconds": 8.022471904754639}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        \n", "entropy": 3.9832653999328613, "length": 256, "finished": false, "message": null, "duration_seconds": 8.261077642440796}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        \n", "entropy": 3.9832653999328613, "length": 256, "finished": false, "message": null, "duration_seconds": 8.253549814224243}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        \n", "entropy": 3.9832653999328613, "length": 256, "finished": false, "message": null, "duration_seconds": 8.455929279327393}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int i = 0;\n", "entropy": 4.413419723510742, "length": 256, "finished": false, "message": null, "duration_seconds": 8.411743640899658}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int i = 0;\n", "entropy": 4.413419723510742, "length": 256, "finished": false, "message": null, "duration_seconds": 8.046152591705322}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int i = 0;\n", "entropy": 4.413419723510742, "length": 256, "finished": false, "message": null, "duration_seconds": 8.097343444824219}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int diff = total - coins[0];\n", "entropy": 4.61262845993042, "length": 256, "finished": false, "message": null, "duration_seconds": 8.066957712173462}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int diff = total - coins[0];\n", "entropy": 4.61262845993042, "length": 256, "finished": false, "message": null, "duration_seconds": 8.094025373458862}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int change = 0;\n", "entropy": 4.63943338394165, "length": 256, "finished": false, "message": null, "duration_seconds": 8.400256395339966}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int changes = 0;\n", "entropy": 4.708052635192871, "length": 256, "finished": false, "message": null, "duration_seconds": 8.390259265899658}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int res = 0;\n", "entropy": 5.168957233428955, "length": 256, "finished": false, "message": null, "duration_seconds": 8.131398439407349}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int result = 0;\n", "entropy": 5.219298362731934, "length": 256, "finished": false, "message": null, "duration_seconds": 9.43195915222168}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int count = 0;\n", "entropy": 5.245595932006836, "length": 256, "finished": false, "message": null, "duration_seconds": 8.124644756317139}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int possible = 0;\n", "entropy": 5.262577056884766, "length": 256, "finished": false, "message": null, "duration_seconds": 8.054859638214111}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int ret = 0;\n", "entropy": 5.563676834106445, "length": 256, "finished": false, "message": null, "duration_seconds": 8.068029880523682}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int c = 0;\n", "entropy": 5.627986431121826, "length": 256, "finished": false, "message": null, "duration_seconds": 8.121924638748169}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        Arrays.sort(coins);\n", "entropy": 5.722962856292725, "length": 256, "finished": false, "message": null, "duration_seconds": 8.012810707092285}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int i = 0;\n", "entropy": 5.810634136199951, "length": 256, "finished": false, "message": null, "duration_seconds": 8.028533697128296}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int changed = 0;\n", "entropy": 5.831117630004883, "length": 256, "finished": false, "message": null, "duration_seconds": 8.271398067474365}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int diff = total - coins[0];\n", "entropy": 6.325314998626709, "length": 256, "finished": false, "message": null, "duration_seconds": 8.065702438354492}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        else if (total == 1) {\n", "entropy": 6.379978179931641, "length": 256, "finished": false, "message": null, "duration_seconds": 8.147832155227661}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int possible = 0;\n", "entropy": 6.429104328155518, "length": 256, "finished": false, "message": null, "duration_seconds": 8.092194557189941}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int possible = 0;\n", "entropy": 6.429104328155518, "length": 256, "finished": false, "message": null, "duration_seconds": 8.494631052017212}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int r = 0;\n", "entropy": 6.443682670593262, "length": 256, "finished": false, "message": null, "duration_seconds": 8.168798685073853}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int len = coins.length;\n", "entropy": 6.600898742675781, "length": 256, "finished": false, "message": null, "duration_seconds": 8.728230237960815}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int possible = 1;\n", "entropy": 7.067147254943848, "length": 256, "finished": false, "message": null, "duration_seconds": 8.154982089996338}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] coins1 = new int[total];\n", "entropy": 7.373083114624023, "length": 256, "finished": false, "message": null, "duration_seconds": 8.024569272994995}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        if (coins.length < total) {\n", "entropy": 7.5098371505737305, "length": 256, "finished": false, "message": null, "duration_seconds": 7.996886730194092}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] changes = new int[total];\n", "entropy": 7.512045860290527, "length": 256, "finished": false, "message": null, "duration_seconds": 8.080628156661987}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        return possible_change(coins, total - 1) + 1;\n", "entropy": 7.572807788848877, "length": 256, "finished": false, "message": null, "duration_seconds": 8.078474044799805}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int diff = total - coins[1];\n", "entropy": 7.601092338562012, "length": 256, "finished": false, "message": null, "duration_seconds": 8.320330619812012}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        if (coins.length == 0 || coins.length == total) {\n", "entropy": 7.727932453155518, "length": 256, "finished": false, "message": null, "duration_seconds": 8.08948802947998}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] p = new int[total];\n", "entropy": 7.736576080322266, "length": 256, "finished": false, "message": null, "duration_seconds": 8.18066692352295}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        total--;\n", "entropy": 7.925263404846191, "length": 256, "finished": false, "message": null, "duration_seconds": 8.489114046096802}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int best_change = Integer.MAX_VALUE;\n", "entropy": 8.140361785888672, "length": 256, "finished": false, "message": null, "duration_seconds": 8.166595935821533}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int n = Math.min(total, coins.length);\n", "entropy": 8.421168327331543, "length": 256, "finished": false, "message": null, "duration_seconds": 8.163386583328247}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] possible = new int[coins.length];\n", "entropy": 8.494270324707031, "length": 256, "finished": false, "message": null, "duration_seconds": 8.069309949874878}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] coins2 = new int[coins.length];\n", "entropy": 8.515978813171387, "length": 256, "finished": false, "message": null, "duration_seconds": 8.036985635757446}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int min = Math.min(coins[0], coins[total - 1]);\n", "entropy": 9.002996444702148, "length": 256, "finished": false, "message": null, "duration_seconds": 8.162940740585327}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int total_new = 0;\n", "entropy": 9.105737686157227, "length": 256, "finished": false, "message": null, "duration_seconds": 8.285958528518677}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] swap = new int[total];\n", "entropy": 9.138908386230469, "length": 256, "finished": false, "message": null, "duration_seconds": 8.427268505096436}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int total2 = total / 2;\n", "entropy": 9.19128131866455, "length": 256, "finished": false, "message": null, "duration_seconds": 8.106149673461914}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] nextCoins = new int[total];\n", "entropy": 9.509629249572754, "length": 256, "finished": false, "message": null, "duration_seconds": 8.06239628791809}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int possible = coins[0];\n", "entropy": 9.643537521362305, "length": 256, "finished": false, "message": null, "duration_seconds": 8.571619272232056}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        if (coins.length < 2) {\n", "entropy": 9.840731620788574, "length": 256, "finished": false, "message": null, "duration_seconds": 8.236806154251099}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int first = 0, second = 0;\n", "entropy": 10.168848991394043, "length": 256, "finished": false, "message": null, "duration_seconds": 8.100126028060913}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] profit = new int[total];\n", "entropy": 10.349302291870117, "length": 256, "finished": false, "message": null, "duration_seconds": 8.125428676605225}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int ind = 0;\n", "entropy": 10.650586128234863, "length": 256, "finished": false, "message": null, "duration_seconds": 9.07215142250061}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int allowed = 0;\n", "entropy": 10.898650169372559, "length": 256, "finished": false, "message": null, "duration_seconds": 8.029703617095947}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] coins_prime = new int[total];\n", "entropy": 11.061105728149414, "length": 256, "finished": false, "message": null, "duration_seconds": 8.091001033782959}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        Set<Integer> set = new HashSet<>(coins.length);\n", "entropy": 11.158590316772461, "length": 256, "finished": false, "message": null, "duration_seconds": 8.099354982376099}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int sum  = 0;\n", "entropy": 11.354033470153809, "length": 256, "finished": false, "message": null, "duration_seconds": 8.233321905136108}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        if (coins[0] == total || coins[1] == total) {\n", "entropy": 11.362858772277832, "length": 256, "finished": false, "message": null, "duration_seconds": 8.542397260665894}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int min_coins = coins[0];\n", "entropy": 11.417206764221191, "length": 256, "finished": false, "message": null, "duration_seconds": 8.66591191291809}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        if (coins.length == 0 || total < coins.length) {\n", "entropy": 11.701932907104492, "length": 256, "finished": false, "message": null, "duration_seconds": 8.640126705169678}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int[] allCoins = new int[coins.length];\n", "entropy": 11.789519309997559, "length": 256, "finished": false, "message": null, "duration_seconds": 8.03575611114502}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int r = 2;\n", "entropy": 11.84342098236084, "length": 256, "finished": false, "message": null, "duration_seconds": 8.16677975654602}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int total_plus_coins = total + coins[0];\n", "entropy": 12.09870719909668, "length": 256, "finished": false, "message": null, "duration_seconds": 8.851469993591309}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] parent = coins[0];\n", "entropy": 12.870585441589355, "length": 256, "finished": false, "message": null, "duration_seconds": 8.055943489074707}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        return Math.min(Math.max(0, total - coins[0]), total - coins[1]);\n", "entropy": 12.917001724243164, "length": 256, "finished": false, "message": null, "duration_seconds": 8.399840593338013}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        return coins.length - (total - 1);\n", "entropy": 13.170358657836914, "length": 256, "finished": false, "message": null, "duration_seconds": 8.146413803100586}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        List<List<Integer>> list = new ArrayList<>(total);\n", "entropy": 13.270377159118652, "length": 256, "finished": false, "message": null, "duration_seconds": 8.116976499557495}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int n = coins.length, d = total;\n", "entropy": 13.604805946350098, "length": 256, "finished": false, "message": null, "duration_seconds": 8.155908823013306}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] gen = new int[total];\n", "entropy": 14.166524887084961, "length": 256, "finished": false, "message": null, "duration_seconds": 8.206641435623169}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        if (coins[0] - 1 > total) {\n", "entropy": 14.274581909179688, "length": 256, "finished": false, "message": null, "duration_seconds": 8.106512546539307}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int z = coins.length;\n", "entropy": 14.610464096069336, "length": 256, "finished": false, "message": null, "duration_seconds": 8.126473426818848}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int last_coin_num = coins[coins.length - 1];\n", "entropy": 14.984745979309082, "length": 256, "finished": false, "message": null, "duration_seconds": 8.480898380279541}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int[] newCol = new int[total];\n", "entropy": 15.905181884765625, "length": 256, "finished": false, "message": null, "duration_seconds": 8.734493255615234}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[][] possible_changes = new int[coins.length + 1][2];\n", "entropy": 16.104534149169922, "length": 256, "finished": false, "message": null, "duration_seconds": 8.087598085403442}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        if (coins == null || coins[0] == 0 || coins[1] == 0 || coins[2] == 0) {\n", "entropy": 16.144485473632812, "length": 256, "finished": false, "message": null, "duration_seconds": 8.130558967590332}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int to_insert = total - 1;\n", "entropy": 16.311607360839844, "length": 256, "finished": false, "message": null, "duration_seconds": 8.082281112670898}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int num_coins_total = 0;\n", "entropy": 16.491430282592773, "length": 256, "finished": false, "message": null, "duration_seconds": 8.12015175819397}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] coins_as_arr = new int[total];\n", "entropy": 17.59242820739746, "length": 256, "finished": false, "message": null, "duration_seconds": 8.047729969024658}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        final int[] player = new int[total];\n", "entropy": 19.541061401367188, "length": 256, "finished": false, "message": null, "duration_seconds": 8.032178163528442}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int difference = coins[0] == total ? 1 : 0;\n", "entropy": 19.67972755432129, "length": 256, "finished": false, "message": null, "duration_seconds": 7.9601569175720215}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        // if there's no change\n", "entropy": 19.93004608154297, "length": 256, "finished": false, "message": null, "duration_seconds": 8.478153944015503}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int word_total = total / 2;\n", "entropy": 20.770906448364258, "length": 256, "finished": false, "message": null, "duration_seconds": 8.095934629440308}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        if (coinarray(coins, 0, total) > total) {\n", "entropy": 20.876279830932617, "length": 256, "finished": false, "message": null, "duration_seconds": 8.057373762130737}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "\n        int[] coins_old = new int[selected_coins.length];\n", "entropy": 21.098779678344727, "length": 256, "finished": false, "message": null, "duration_seconds": 8.04789924621582}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        return (int) coins[(int) Math.ceil(Math.log(total))] + 1;\n", "entropy": 23.259546279907227, "length": 256, "finished": false, "message": null, "duration_seconds": 8.789865970611572}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[] coins_plus_one_score = new int[total + 1];\n", "entropy": 23.880447387695312, "length": 256, "finished": false, "message": null, "duration_seconds": 8.881720781326294}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int mid = Math.max(0, (coins[total - 1] + coins[total]) / 2) + coins[total - 1];\n", "entropy": 27.929309844970703, "length": 256, "finished": false, "message": null, "duration_seconds": 8.567643642425537}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        int[][] main_position = new int[total + 1][(total - 1)];\n", "entropy": 28.405017852783203, "length": 256, "finished": false, "message": null, "duration_seconds": 8.272068977355957}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        return add(total-coins[0], coins[1], total-coins[1]);\n", "entropy": 29.01253318786621, "length": 256, "finished": false, "message": null, "duration_seconds": 8.039228677749634}
{"context": "package java_programs;\nimport java.util.*;\n\npublic class POSSIBLE_CHANGE {\n    public static int possible_change(int[] coins, int total) {\n        if (total == 0) {\n            return 1;\n        }\n", "text": "        /* Find best such that coins[pos] < total */\n", "entropy": 34.32447814941406, "length": 256, "finished": false, "message": null, "duration_seconds": 8.249030113220215}
