{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.206199645996094}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.391333818435669}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.292705059051514}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.275614261627197}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.275383949279785}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.1652138233184814}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.0996832847595215}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.176552772521973}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.273220777511597}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.216614007949829}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.187338352203369}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.226638078689575}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.297598600387573}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.223138332366943}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.2869040966033936}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.155285120010376}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.3285956382751465}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.427210330963135}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.266185998916626}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.356525182723999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.348861932754517}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.1611199378967285}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.3106443881988525}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.246413946151733}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.229480743408203}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.24617600440979}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.179933071136475}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.2575178146362305}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.2373692989349365}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.1409337520599365}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.208911895751953}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.242213487625122}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.206836223602295}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.266251802444458}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.298065662384033}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.264016389846802}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.402659893035889}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.520328760147095}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.251147270202637}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.21890664100647}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.378592014312744}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.2660605907440186}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.279135704040527}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.28049898147583}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.342926263809204}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.7196444272994995, "length": 256, "finished": false, "message": null, "duration_seconds": 4.3857550621032715}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.429710388183594}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.247366905212402}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.209631443023682}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.393073797225952}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.578372001647949}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.4080588817596436}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.208448648452759}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.2994091510772705}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.19865870475769}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.326741695404053}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.128633260726929}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.319063425064087}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 2.4275052547454834, "length": 256, "finished": false, "message": null, "duration_seconds": 4.1596479415893555}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo > 1) {\n", "entropy": 3.17356276512146, "length": 256, "finished": false, "message": null, "duration_seconds": 4.10955023765564}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo > 1) {\n", "entropy": 3.17356276512146, "length": 256, "finished": false, "message": null, "duration_seconds": 4.1863744258880615}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo > 1) {\n", "entropy": 3.17356276512146, "length": 256, "finished": false, "message": null, "duration_seconds": 4.538841009140015}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo > 1) {\n", "entropy": 3.17356276512146, "length": 256, "finished": false, "message": null, "duration_seconds": 4.1478893756866455}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi > lo) {\n", "entropy": 3.5100979804992676, "length": 256, "finished": false, "message": null, "duration_seconds": 4.174330949783325}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi > lo) {\n", "entropy": 3.5100979804992676, "length": 256, "finished": false, "message": null, "duration_seconds": 4.240805387496948}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi > lo) {\n", "entropy": 3.5100979804992676, "length": 256, "finished": false, "message": null, "duration_seconds": 4.198570251464844}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.670437812805176, "length": 256, "finished": false, "message": null, "duration_seconds": 4.260413646697998}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.670437812805176, "length": 256, "finished": false, "message": null, "duration_seconds": 4.1019463539123535}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.670437812805176, "length": 256, "finished": false, "message": null, "duration_seconds": 4.240397691726685}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.670437812805176, "length": 256, "finished": false, "message": null, "duration_seconds": 4.167042970657349}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.670437812805176, "length": 256, "finished": false, "message": null, "duration_seconds": 4.180305004119873}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (int i = 0; i < hi; i++) {\n", "entropy": 3.7533082962036133, "length": 256, "finished": false, "message": null, "duration_seconds": 4.249437093734741}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (int i = 0; i < hi; i++) {\n", "entropy": 3.7533082962036133, "length": 256, "finished": false, "message": null, "duration_seconds": 4.16501522064209}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo > 0) {\n", "entropy": 3.8793766498565674, "length": 256, "finished": false, "message": null, "duration_seconds": 4.109355688095093}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (int i = 0; i < lo; i++) {\n", "entropy": 4.655280590057373, "length": 256, "finished": false, "message": null, "duration_seconds": 4.179277420043945}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (int i = 0; i < lo; i++) {\n", "entropy": 4.655280590057373, "length": 256, "finished": false, "message": null, "duration_seconds": 4.220696687698364}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (int i = 0; i < lo; i++) {\n", "entropy": 4.655280590057373, "length": 256, "finished": false, "message": null, "duration_seconds": 4.342890024185181}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (int i = 0; i < lo; i++) {\n", "entropy": 4.655280590057373, "length": 256, "finished": false, "message": null, "duration_seconds": 4.3104541301727295}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (int i = 0; i < lo; i++) {\n", "entropy": 4.655280590057373, "length": 256, "finished": false, "message": null, "duration_seconds": 4.492425203323364}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo >= 1) {\n", "entropy": 5.124453067779541, "length": 256, "finished": false, "message": null, "duration_seconds": 4.302022457122803}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < lo + hi) {\n", "entropy": 5.165282726287842, "length": 256, "finished": false, "message": null, "duration_seconds": 4.318562269210815}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo < x) {\n", "entropy": 5.30784797668457, "length": 256, "finished": false, "message": null, "duration_seconds": 4.210404634475708}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo <= hi) {\n", "entropy": 5.5739240646362305, "length": 256, "finished": false, "message": null, "duration_seconds": 4.214407444000244}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo >= 0) {\n", "entropy": 5.641453266143799, "length": 256, "finished": false, "message": null, "duration_seconds": 4.14591383934021}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "\n        while (lo < hi) {\n", "entropy": 5.982860565185547, "length": 256, "finished": false, "message": null, "duration_seconds": 4.278517961502075}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (int i = lo; i <= hi; i++) {\n", "entropy": 6.0057373046875, "length": 256, "finished": false, "message": null, "duration_seconds": 4.184230327606201}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo != hi) {\n", "entropy": 6.071158409118652, "length": 256, "finished": false, "message": null, "duration_seconds": 4.164903163909912}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo != hi) {\n", "entropy": 6.071158409118652, "length": 256, "finished": false, "message": null, "duration_seconds": 4.090080976486206}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        if (x < lo) {\n", "entropy": 6.2986555099487305, "length": 256, "finished": false, "message": null, "duration_seconds": 4.117498397827148}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi && arr[lo] <= x) lo++;\n", "entropy": 6.986519813537598, "length": 256, "finished": false, "message": null, "duration_seconds": 4.312514781951904}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for (;;) {\n", "entropy": 8.111595153808594, "length": 256, "finished": false, "message": null, "duration_seconds": 4.256446361541748}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi-- > 0) {\n", "entropy": 8.235578536987305, "length": 256, "finished": false, "message": null, "duration_seconds": 4.3535566329956055}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi-lo > 0) {\n", "entropy": 8.55183219909668, "length": 256, "finished": false, "message": null, "duration_seconds": 4.3087873458862305}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "\n        for (int i = 0; i < hi; i++) {\n", "entropy": 8.679067611694336, "length": 256, "finished": false, "message": null, "duration_seconds": 4.26163387298584}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        int mid = (lo+hi)/2;\n", "entropy": 9.605953216552734, "length": 256, "finished": false, "message": null, "duration_seconds": 4.3333306312561035}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        for(int i = 0; i < lo; i++)\n", "entropy": 10.902652740478516, "length": 256, "finished": false, "message": null, "duration_seconds": 4.224096059799194}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        int mid = arr[lo++];\n", "entropy": 14.436123847961426, "length": 256, "finished": false, "message": null, "duration_seconds": 4.211831092834473}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (y = arr[lo]) {\n", "entropy": 14.682984352111816, "length": 256, "finished": false, "message": null, "duration_seconds": 4.202454328536987}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        System.out.println(\"Remembering \" + lo);\n", "entropy": 27.884811401367188, "length": 256, "finished": false, "message": null, "duration_seconds": 4.182626962661743}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        //\u5982\u679c\u6709\u73af\u5e8f\u94fe\uff0c\u76f4\u63a5\u8fd4\u56de\u6700\u589e\u7684\u7b2c\u4e00\u4e2a\u5e76\u8fd4\u56de\u5176\u8865\u9f50\u6700\u540e\n", "entropy": 85.83943176269531, "length": 256, "finished": false, "message": null, "duration_seconds": 4.232581615447998}
