{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9825572787807997}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.989226096722}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9892910953265}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9899789846508}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9909955779308}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9914031307907998}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9916903973508}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9965055412507999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9974396307265003}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9990769863507999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9991619703665}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 0.9993521319508}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0026731433682}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0029071893681998}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0034276005665002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0047222870581998}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0047933739865003}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0085105748265002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0087357939865}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.009459044912}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0099324066764999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0110397221265002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0115354590908001}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0129997827665}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0138543283393002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0140910277819999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.014560844963}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0149254441865}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.015167646862}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0153890461882}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0157200768608}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0161771964508002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0164101807681998}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.016701920982}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0167716134508}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0171008684282}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0177474503882}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0177474683882002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0180363561908}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0207124446282}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0209697294693}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0217439022865}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0232219499265}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0248069468765}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0254936812265}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0274455129681999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0274593341682001}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0289582250865}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0299361124893}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0330907060738002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.036780931982}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0368941027037997}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.0488341351508002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 1.056621156922}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.17859284724}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.199162819500001}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.200191660439999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.215719814990001}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.2177659216800003}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.2208638469}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.2208793245799994}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.23382139057}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.2446258350899995}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.245498971209999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.27136233732}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.2724422892500002}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.2756717201599996}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.2788287985799993}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.29399921944}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.31065104515}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.3158567787600006}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.3188599832299994}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.32111858262}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 2.3282152422399998}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 3.3966766290692996}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 3.4599590541507994}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result += alphabet.charAt(i);", "entropy": 2.314770951721499}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result += alphabet.charAt(i);", "entropy": 2.323770794377}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result += alphabet.charAt(i);", "entropy": 2.329640065848999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result += alphabet.charAt(i);", "entropy": 2.3797975867415}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result += alphabet.charAt(i);", "entropy": 2.3858250247129997}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result += alphabet.charAt(i);", "entropy": 2.387586831583001}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result += alphabet.charAt(i);", "entropy": 2.400619853622}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result += alphabet.charAt(i);", "entropy": 2.402908206922}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i+1) + result;", "entropy": 4.2599613740099995}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i+1) + result;", "entropy": 4.34417822447}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result;", "entropy": 5.16058682397}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = result + alphabet.charAt(i);", "entropy": 3.264272686327}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = result + alphabet.charAt(i);", "entropy": 3.4003689576759997}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 5.6328644405593}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + \"\" + result;", "entropy": 6.6578328493093}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 7.6058708615308}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 8.857673377226499}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            if (i < 10) {", "entropy": 6.571204989000001}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            if (i > 9) {", "entropy": 6.981367970999999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            if (i < 10)", "entropy": 7.265592142999999}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            //result = result.concat(alphabet.charAt(i));", "entropy": 12.4428319248}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.substring(i, i + 1) + result; // How does it work?", "entropy": 17.198200022099993}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            result = alphabet.charAt(i) + result;", "entropy": 13.179846258206501}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class TO_BASE {\n    public static String to_base(int num, int b) {\n        String result = \"\";\n        String alphabet = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\";\n        int i;\n        while (num > 0) {\n            i = num % b;\n            num = num / b; // floor division?\n", "text": "            if (i < 10)", "entropy": 8.318321736999998}
