{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 14.604304790496826}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.22437286376953}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.281743049621582}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.933525085449219}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.10739517211914}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.41341757774353}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.458250761032104}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.61560583114624}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.651123285293579}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.622548818588257}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.38961124420166}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.731487274169922}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.796280145645142}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.822186946868896}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.951143264770508}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.597349405288696}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.858747720718384}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.90100932121277}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.035885095596313}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.485271453857422}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.72084665298462}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.537949562072754}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.63295340538025}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.618754863739014}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.734286546707153}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.17144465446472}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.56512427330017}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.121641159057617}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 18.2301127910614}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.148141384124756}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.901981353759766}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.276982069015503}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.447365760803223}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.00152325630188}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.83987808227539}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.21211576461792}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.889140129089355}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.464574575424194}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.899566650390625}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.76410984992981}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.520256996154785}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.997424840927124}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.643340587615967}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.419382572174072}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.72679877281189}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.608184814453125}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.546640157699585}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 18.28910255432129}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.64828062057495}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.329949378967285}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.390830755233765}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.15210771560669}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 20.3388991355896}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.762712240219116}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.630908250808716}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 18.135933876037598}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.183459997177124}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.512459993362427}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.512449502944946}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.51379942893982}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 18.2836971282959}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.917227506637573}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.672972202301025}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.324146032333374}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.559630155563354}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 17.18662929534912}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.615901470184326}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.47624182701111}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 15.626851081848145}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.578715801239014}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 18.67143750190735}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.368686199188232}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.43026304244995}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) {\n", "entropy": 0.299502432346344, "length": 256, "finished": false, "message": null, "duration_seconds": 16.71506142616272}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 3.10029935836792, "length": 256, "finished": false, "message": null, "duration_seconds": 16.16410255432129}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 3.10029935836792, "length": 256, "finished": false, "message": null, "duration_seconds": 16.27251935005188}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 3.10029935836792, "length": 256, "finished": false, "message": null, "duration_seconds": 19.857816457748413}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 3.10029935836792, "length": 256, "finished": false, "message": null, "duration_seconds": 17.858673810958862}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo <= hi) {\n", "entropy": 3.10029935836792, "length": 256, "finished": false, "message": null, "duration_seconds": 16.661394834518433}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo > 1) {\n", "entropy": 3.3163092136383057, "length": 256, "finished": false, "message": null, "duration_seconds": 16.154471397399902}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo > 1) {\n", "entropy": 3.3163092136383057, "length": 256, "finished": false, "message": null, "duration_seconds": 16.58335256576538}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (hi - lo > 1) {\n", "entropy": 3.3163092136383057, "length": 256, "finished": false, "message": null, "duration_seconds": 15.951009511947632}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi - 1) {\n", "entropy": 3.4390110969543457, "length": 256, "finished": false, "message": null, "duration_seconds": 16.50390362739563}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi - 1) {\n", "entropy": 3.4390110969543457, "length": 256, "finished": false, "message": null, "duration_seconds": 17.525797605514526}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi - 1) {\n", "entropy": 3.4390110969543457, "length": 256, "finished": false, "message": null, "duration_seconds": 16.739503383636475}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.452893018722534, "length": 256, "finished": false, "message": null, "duration_seconds": 15.546536445617676}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.452893018722534, "length": 256, "finished": false, "message": null, "duration_seconds": 16.2153582572937}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.452893018722534, "length": 256, "finished": false, "message": null, "duration_seconds": 16.24135112762451}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.452893018722534, "length": 256, "finished": false, "message": null, "duration_seconds": 16.600106954574585}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.452893018722534, "length": 256, "finished": false, "message": null, "duration_seconds": 15.610501527786255}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.452893018722534, "length": 256, "finished": false, "message": null, "duration_seconds": 16.193350553512573}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi) {\n", "entropy": 3.452893018722534, "length": 256, "finished": false, "message": null, "duration_seconds": 16.37408137321472}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while(lo < hi){\n", "entropy": 4.352128028869629, "length": 256, "finished": false, "message": null, "duration_seconds": 17.29615616798401}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi)\n", "entropy": 4.8102617263793945, "length": 256, "finished": false, "message": null, "duration_seconds": 15.981201648712158}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo + 1 < hi) {\n", "entropy": 5.068431854248047, "length": 256, "finished": false, "message": null, "duration_seconds": 15.924137115478516}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo + 1 < hi) {\n", "entropy": 5.068431854248047, "length": 256, "finished": false, "message": null, "duration_seconds": 16.77079486846924}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo != hi) {\n", "entropy": 5.801711082458496, "length": 256, "finished": false, "message": null, "duration_seconds": 16.610337018966675}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        int i = lo;\n", "entropy": 6.39879846572876, "length": 256, "finished": false, "message": null, "duration_seconds": 18.552743434906006}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        //\u5982\u679c\u6709\u73af\n", "entropy": 20.11756134033203, "length": 256, "finished": false, "message": null, "duration_seconds": 16.14174485206604}
{"context": "package java_programs;\nimport java.util.*;\n\n\npublic class FIND_FIRST_IN_SORTED {\n\n    public static int find_first_in_sorted(int[] arr, int x) {\n        int lo = 0;\n        int hi = arr.length;\n\n", "text": "        while (lo < hi) { // Note that the first element is always < x\n", "entropy": 25.655427932739258, "length": 256, "finished": false, "message": null, "duration_seconds": 16.48647379875183}
