{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.3757305547499996}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.37675136579}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.41689410859}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.4202907108000002}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.42633158539}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.4271301528700002}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.42872345971}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.4309784046100003}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.43184169478}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.43184179478}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.43250592806}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.43576921812}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.44299636609}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.44409512436}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.4467833203000002}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.4551985153099998}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.45747704519}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.45898559169}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.45899749136}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.46084120119}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.46442860706}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.4764828367300002}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.49240498239}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 3.49364715872}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.00653801666}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.076345689549999}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.08119280636}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.08424733656}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.08906552258}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.09133737099}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.303349030940001}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.62195041576}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.63315828119}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.63813149532}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a%b)", "entropy": 4.68033334739}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a%b)", "entropy": 4.7616206265}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.80631649711}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.8679124636}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.87582874478}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.91211693662}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.91289747049}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 4.91858692412}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.12210913976}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.21199124509}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.23149569298}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.30645332048}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.4676200467000005}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a%b)", "entropy": 5.48980941669}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.49888443593}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.553107997830001}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.56090505477}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.57204843585}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.6661312841900004}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.70284069008}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.86138428819}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 5.91759676758}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.03401926676}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.06431289721}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a%b)", "entropy": 6.16526474869}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.17192478662}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.180401494060001}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a%b)", "entropy": 6.204416645489999}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.25088179831}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.46520813943}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.47852495842}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.56182034931}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.575468772820001}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.61868197282}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.62565867099}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.65534572943}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.7396727179700004}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a%b)", "entropy": 6.76821540492}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 6.77316520792}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 7.01982417613}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 7.04930050321}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 7.28609168691}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 7.44113559469}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 7.610790293579999}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 7.78644896505}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 7.930780191669999}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.037398369089999}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.2390656868}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.43038233456}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.43609775445}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.43711234823}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.454091554769999}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.53327991287}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.679859429019999}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.90489516769}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 8.99384704417}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a%b)", "entropy": 9.00017260687}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 9.03328146577}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 9.46750841802}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 9.63779561023}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 9.68818952913}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        gcd(b, a % b)", "entropy": 10.045323743259999}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 10.36655037086}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 10.54171272656}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 10.88169046125}
{"context": "def gcd(a, b):\n    if b == 0:\n        return a\n    else:\n", "text": "        return gcd(b, a % b)", "entropy": 11.01019404819}
